package com.vaijunto.service;
import com.vaijunto.domain.entities.*; import com.vaijunto.dto.*; import com.vaijunto.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.OffsetDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class AdminProvisioningService {
 private final AdminAccountRepository admins; private final AdminInviteRepository invites; private final AdminRecoveryTokenRepository recoveries; private final AdminAuditEventRepository audits; private final PasswordEncoder passwords; private final EmailService email;
 @Transactional public void invite(String actorEmail, AdminInviteRequest request){ var actor=admins.findByEmail(actorEmail).orElseThrow(); String role=validRole(request.getRole()); String raw=token(); invites.save(AdminInvite.builder().email(request.getEmail().trim().toLowerCase()).role(role).tokenHash(hash(raw)).expiresAt(OffsetDateTime.now().plusMinutes(30)).invitedBy(actor).build()); audits.save(AdminAuditEvent.builder().admin(actor).eventType("ADMIN_INVITED").targetType("EMAIL").targetId(request.getEmail()).build()); email.sendAdminLink(request.getEmail(),"Convite administrativo — VaiJunto","Use este código para ativar sua conta administrativa.",raw); }
 /**
  * Passo 1 de 2 da criação de acesso: valida os dados e devolve um segredo TOTP
  * <b>sem gravar nada</b>. A conta só existe depois que quem está criando provar,
  * em {@link #create}, que conseguiu ler um código válido do autenticador — assim
  * ninguém fica com um acesso administrativo impossível de usar.
  */
 @Transactional(readOnly=true) public Map<String,Object> preview(String emailAddress, String requestedRole, String rawPassword) { String normalized=validNewEmail(emailAddress); String role=validRole(requestedRole); validPassword(rawPassword); String secret=Totp.generateSecret(); return Map.of("email",normalized,"role",role,"totpSecret",secret,"totpUri",totpUri(normalized,secret)); }
 /** Passo 2 de 2: confere o código do autenticador contra o segredo do passo 1 e só então persiste a conta. */
 @Transactional public Map<String,Object> create(String actorEmail, String emailAddress, String requestedRole, String rawPassword, String totpSecret, String totpCode) { var actor=admins.findByEmail(actorEmail).orElseThrow(); String normalized=validNewEmail(emailAddress); String role=validRole(requestedRole); validPassword(rawPassword); String secret=totpSecret==null?"":totpSecret.replaceAll("\\s","").toUpperCase(); if(!secret.matches("[A-Z2-7]{16,64}")) throw new IllegalArgumentException("Gere o QR novamente antes de confirmar o código."); if(!Totp.verify(secret,totpCode==null?null:totpCode.trim())) throw new IllegalArgumentException("Código do autenticador inválido. Confira o app e tente de novo."); var account=admins.save(AdminAccount.builder().email(normalized).password(passwords.encode(rawPassword)).role(role).totpSecret(secret).build()); audits.save(AdminAuditEvent.builder().admin(actor).eventType("ADMIN_CREATED").targetType("ADMIN").targetId(account.getId().toString()).build()); return Map.of("id",account.getId(),"email",account.getEmail(),"role",account.getRole()); }
 /**
  * Exclusão lógica: o acesso deixa de autenticar ({@code AdminAuthService} exige
  * {@code isActive}), mas a linha continua no banco porque as trilhas de auditoria
  * apontam para ela. Um super admin não pode se apagar nem apagar o último ativo.
  */
 @Transactional public void setAccountActive(String actorEmail, UUID id, boolean active) { var actor=admins.findByEmail(actorEmail).orElseThrow(); var target=admins.findById(id).orElseThrow(()->new IllegalArgumentException("Administrador não encontrado.")); if(!active){ if(target.getId().equals(actor.getId())) throw new IllegalArgumentException("Você não pode excluir o seu próprio acesso."); if("SUPER_ADMIN".equals(target.getRole()) && admins.findAll().stream().filter(a->"SUPER_ADMIN".equals(a.getRole())&&Boolean.TRUE.equals(a.getIsActive())).count()<=1) throw new IllegalArgumentException("É preciso manter ao menos um super administrador ativo."); } if(Boolean.valueOf(active).equals(target.getIsActive())) return; target.setIsActive(active); admins.save(target); audits.save(AdminAuditEvent.builder().admin(actor).eventType(active?"ADMIN_RESTORED":"ADMIN_SOFT_DELETED").targetType("ADMIN").targetId(id.toString()).build()); }
 private String validNewEmail(String address){ String normalized=address==null?"":address.trim().toLowerCase(); if(!normalized.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")) throw new IllegalArgumentException("Informe um e-mail administrativo válido."); if(admins.findByEmail(normalized).isPresent()) throw new IllegalArgumentException("Este e-mail administrativo já está em uso."); return normalized; }
 private void validPassword(String raw){ if(raw==null||raw.length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); }
 private String totpUri(String address,String secret){ return "otpauth://totp/VaiJunto:"+java.net.URLEncoder.encode(address, StandardCharsets.UTF_8)+"?secret="+secret+"&issuer=VaiJunto&algorithm=SHA1&digits=6&period=30"; }
 @Transactional public void changePassword(String actorEmail, String currentPassword, String newPassword, String totpCode) { var account=admins.findByEmail(actorEmail).orElseThrow(); if (!passwords.matches(currentPassword, account.getPassword())) throw new IllegalArgumentException("A senha atual está incorreta."); if (!Totp.verify(account.getTotpSecret(), totpCode)) throw new IllegalArgumentException("Código do autenticador inválido."); if(newPassword==null||newPassword.length()<12) throw new IllegalArgumentException("A nova senha precisa ter ao menos 12 caracteres."); account.setPassword(passwords.encode(newPassword)); audits.save(AdminAuditEvent.builder().admin(account).eventType("ADMIN_PASSWORD_CHANGED").build()); }
 @Transactional public void accept(AdminInviteAcceptRequest request){ var invite=invites.findByTokenHash(hash(request.getToken())).filter(AdminInvite::usable).orElseThrow(()->new IllegalArgumentException("Convite inválido ou expirado.")); if(admins.findByEmail(invite.getEmail()).isPresent()) throw new IllegalArgumentException("Este e-mail administrativo já está em uso."); if(request.getPassword()==null||request.getPassword().length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); if(request.getTotpSecret()==null||request.getTotpSecret().isBlank()) throw new IllegalArgumentException("Configure seu autenticador antes de ativar a conta."); var account=admins.save(AdminAccount.builder().email(invite.getEmail()).password(passwords.encode(request.getPassword())).role(invite.getRole()).totpSecret(request.getTotpSecret().replaceAll("\\s","").toUpperCase()).build()); invite.setConsumedAt(OffsetDateTime.now()); audits.save(AdminAuditEvent.builder().admin(account).eventType("ADMIN_INVITE_ACCEPTED").build()); }
 @Transactional public void requestRecovery(String address){ admins.findByEmail(address.trim().toLowerCase()).ifPresent(admin->{String raw=token(); recoveries.save(AdminRecoveryToken.builder().admin(admin).tokenHash(hash(raw)).expiresAt(OffsetDateTime.now().plusMinutes(30)).build()); audits.save(AdminAuditEvent.builder().admin(admin).eventType("ADMIN_RECOVERY_REQUESTED").build()); email.sendAdminLink(admin.getEmail(),"Recuperação administrativa — VaiJunto","Use este código e seu autenticador para redefinir a senha.",raw);}); }
 @Transactional public void confirmRecovery(AdminRecoveryConfirmRequest request){ var recovery=recoveries.findByTokenHash(hash(request.getToken())).filter(AdminRecoveryToken::usable).orElseThrow(()->new IllegalArgumentException("Recuperação inválida ou expirada.")); var admin=recovery.getAdmin(); if(!Totp.verify(admin.getTotpSecret(),request.getTotpCode())) throw new IllegalArgumentException("Código do autenticador inválido."); if(request.getPassword()==null||request.getPassword().length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); admin.setPassword(passwords.encode(request.getPassword())); recovery.setConsumedAt(OffsetDateTime.now()); audits.save(AdminAuditEvent.builder().admin(admin).eventType("ADMIN_RECOVERY_CONFIRMED").build()); }
 private String validRole(String role){if(!Set.of("ADMIN","MODERATOR").contains(role))throw new IllegalArgumentException("Convites só podem criar ADMIN ou MODERATOR.");return role;}
 private String token(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
