package com.vaijunto.service;
import com.vaijunto.domain.entities.*; import com.vaijunto.dto.*; import com.vaijunto.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.OffsetDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class AdminProvisioningService {
 private final AdminAccountRepository admins; private final AdminInviteRepository invites; private final AdminRecoveryTokenRepository recoveries; private final AdminAuditEventRepository audits; private final PasswordEncoder passwords; private final EmailService email;
 @Transactional public void invite(String actorEmail, AdminInviteRequest request){ var actor=admins.findByEmail(actorEmail).orElseThrow(); String role=validRole(request.getRole()); String raw=token(); invites.save(AdminInvite.builder().email(request.getEmail().trim().toLowerCase()).role(role).tokenHash(hash(raw)).expiresAt(OffsetDateTime.now().plusMinutes(30)).invitedBy(actor).build()); audits.save(AdminAuditEvent.builder().admin(actor).eventType("ADMIN_INVITED").targetType("EMAIL").targetId(request.getEmail()).build()); email.sendAdminLink(request.getEmail(),"Convite administrativo — VaiJunto","Use este código para ativar sua conta administrativa.",raw); }
 @Transactional public Map<String,Object> create(String actorEmail, String emailAddress, String requestedRole, String rawPassword) { var actor=admins.findByEmail(actorEmail).orElseThrow(); String normalized=emailAddress==null ? "" : emailAddress.trim().toLowerCase(); if (!normalized.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")) throw new IllegalArgumentException("Informe um e-mail administrativo válido."); if (admins.findByEmail(normalized).isPresent()) throw new IllegalArgumentException("Este e-mail administrativo já está em uso."); if(rawPassword==null||rawPassword.length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); String role=validRole(requestedRole); String secret=Totp.generateSecret(); var account=admins.save(AdminAccount.builder().email(normalized).password(passwords.encode(rawPassword)).role(role).totpSecret(secret).build()); audits.save(AdminAuditEvent.builder().admin(actor).eventType("ADMIN_CREATED").targetType("ADMIN").targetId(account.getId().toString()).build()); String uri="otpauth://totp/VaiJunto:"+java.net.URLEncoder.encode(normalized, StandardCharsets.UTF_8)+"?secret="+secret+"&issuer=VaiJunto&algorithm=SHA1&digits=6&period=30"; return Map.of("id",account.getId(),"email",account.getEmail(),"role",account.getRole(),"totpSecret",secret,"totpUri",uri); }
 @Transactional public void changePassword(String actorEmail, String currentPassword, String newPassword, String totpCode) { var account=admins.findByEmail(actorEmail).orElseThrow(); if (!passwords.matches(currentPassword, account.getPassword())) throw new IllegalArgumentException("A senha atual está incorreta."); if (!Totp.verify(account.getTotpSecret(), totpCode)) throw new IllegalArgumentException("Código do autenticador inválido."); if(newPassword==null||newPassword.length()<12) throw new IllegalArgumentException("A nova senha precisa ter ao menos 12 caracteres."); account.setPassword(passwords.encode(newPassword)); audits.save(AdminAuditEvent.builder().admin(account).eventType("ADMIN_PASSWORD_CHANGED").build()); }
 @Transactional public void accept(AdminInviteAcceptRequest request){ var invite=invites.findByTokenHash(hash(request.getToken())).filter(AdminInvite::usable).orElseThrow(()->new IllegalArgumentException("Convite inválido ou expirado.")); if(admins.findByEmail(invite.getEmail()).isPresent()) throw new IllegalArgumentException("Este e-mail administrativo já está em uso."); if(request.getPassword()==null||request.getPassword().length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); if(request.getTotpSecret()==null||request.getTotpSecret().isBlank()) throw new IllegalArgumentException("Configure seu autenticador antes de ativar a conta."); var account=admins.save(AdminAccount.builder().email(invite.getEmail()).password(passwords.encode(request.getPassword())).role(invite.getRole()).totpSecret(request.getTotpSecret().replaceAll("\\s","").toUpperCase()).build()); invite.setConsumedAt(OffsetDateTime.now()); audits.save(AdminAuditEvent.builder().admin(account).eventType("ADMIN_INVITE_ACCEPTED").build()); }
 @Transactional public void requestRecovery(String address){ admins.findByEmail(address.trim().toLowerCase()).ifPresent(admin->{String raw=token(); recoveries.save(AdminRecoveryToken.builder().admin(admin).tokenHash(hash(raw)).expiresAt(OffsetDateTime.now().plusMinutes(30)).build()); audits.save(AdminAuditEvent.builder().admin(admin).eventType("ADMIN_RECOVERY_REQUESTED").build()); email.sendAdminLink(admin.getEmail(),"Recuperação administrativa — VaiJunto","Use este código e seu autenticador para redefinir a senha.",raw);}); }
 @Transactional public void confirmRecovery(AdminRecoveryConfirmRequest request){ var recovery=recoveries.findByTokenHash(hash(request.getToken())).filter(AdminRecoveryToken::usable).orElseThrow(()->new IllegalArgumentException("Recuperação inválida ou expirada.")); var admin=recovery.getAdmin(); if(!Totp.verify(admin.getTotpSecret(),request.getTotpCode())) throw new IllegalArgumentException("Código do autenticador inválido."); if(request.getPassword()==null||request.getPassword().length()<12) throw new IllegalArgumentException("A senha precisa ter ao menos 12 caracteres."); admin.setPassword(passwords.encode(request.getPassword())); recovery.setConsumedAt(OffsetDateTime.now()); audits.save(AdminAuditEvent.builder().admin(admin).eventType("ADMIN_RECOVERY_CONFIRMED").build()); }
 private String validRole(String role){if(!Set.of("ADMIN","MODERATOR").contains(role))throw new IllegalArgumentException("Convites só podem criar ADMIN ou MODERATOR.");return role;}
 private String token(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
