package com.vaijunto.service;

import com.vaijunto.domain.entities.*;
import com.vaijunto.exception.ApiException;
import com.vaijunto.repository.*;
import java.time.OffsetDateTime;
import java.util.*;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Administrative boundary: report views are limited to immutable selected evidence. */
@Service @RequiredArgsConstructor
public class AdminOperationsService {
 private final AdminAccountRepository admins; private final AdminAuditEventRepository audits; private final UserRepository users; private final MessageReportRepository reports; private final ReportEvidenceSnapshotRepository evidence; private final ChatStickerRepository stickers; private final NotificationService notifications; private final ConversationRepository conversations; private final ConversationMessageRepository messages; private final VehicleRepository vehicles; private final OfferRepository offers; private final MediaStorageService storage; private final AdminUserTagRepository userTags; private final AdminUserTagAssignmentRepository tagAssignments; private final MediaObjectRepository mediaObjects;
 @Transactional public Map<String,Object> verify(String email, UUID id,String action,String reason){var u=user(id);var a=action(action,Set.of("GRANT","REJECT","PAUSE","REMOVE"));reason(reason);u.setVerificationBadgeActive("GRANT".equals(a));u.setVerificationStatus(switch(a){case "GRANT"->"VERIFIED";case "REJECT"->"REJECTED";case "PAUSE"->"PAUSED";default->"REMOVED";});u.setVerificationNote(reason.trim());audit(email,"VERIFICATION_"+a,"USER",id.toString(),reason);notifications.createAndSendNotification(id,"VaiJunto","Seu selo de verificação foi atualizado.","VERIFICATION_UPDATED","{}",null);return summary(u);}
 @Transactional public Map<String,Object> moderate(String email,UUID id,String action,String reason){var u=user(id);var a=action(action,Set.of("WARN","CLEAR_WARNING","SUSPEND","RESTORE"));if(!Set.of("CLEAR_WARNING","RESTORE").contains(a))reason(reason);if("WARN".equals(a)){u.setWarnedAt(OffsetDateTime.now());u.setWarningReason(reason.trim());}if("CLEAR_WARNING".equals(a)){u.setWarnedAt(null);u.setWarningReason(null);}if("SUSPEND".equals(a)){u.setIsActive(false);u.setSuspendedAt(OffsetDateTime.now());u.setSuspensionReason(reason.trim());}if("RESTORE".equals(a)){u.setIsActive(u.getDeletionRequestedAt()==null);u.setSuspendedAt(null);u.setSuspensionReason(null);}audit(email,"USER_"+a,"USER",id.toString(),reason);notifications.createAndSendNotification(id,"VaiJunto","Há uma atualização na sua conta. Consulte o canal oficial.","MODERATION_UPDATED","{}",null);return summary(u);}
 @Transactional(readOnly=true) public List<Map<String,Object>> search(String query){var q=query==null?"":query.trim();if(q.length()<2)throw new ApiException(HttpStatus.BAD_REQUEST,"SEARCH_TOO_SHORT","Digite ao menos 2 caracteres.");return users.findTop50ByNameContainingIgnoreCaseOrFullNameContainingIgnoreCaseOrEmailContainingIgnoreCase(q,q,q).stream().map(this::summary).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> recentUsers(){return users.findTop50ByOrderByCreatedAtDesc().stream().map(this::summary).toList();}
 /**
  * Exclusão lógica de uma conta da comunidade: a pessoa perde o login
  * ({@code UserDetailsServiceImpl} usa {@code isActive} como enabled) e fica
  * marcada com {@code deletionRequestedAt}, mas nada é apagado — histórico de
  * caronas, denúncias e mensagens continuam referenciando o registro. RESTORE
  * desfaz enquanto a conta ainda não tiver sido anonimizada.
  */
 @Transactional public Map<String,Object> setDeleted(String email,UUID id,String action,String reason){var u=user(id);var a=action(action,Set.of("DELETE","RESTORE"));if("DELETE".equals(a)){reason(reason);if(u.getAnonymizedAt()!=null)throw new ApiException(HttpStatus.BAD_REQUEST,"USER_ALREADY_ANONYMIZED","Esta conta já foi anonimizada.");u.setDeletionRequestedAt(OffsetDateTime.now());u.setIsActive(false);}else{if(u.getAnonymizedAt()!=null)throw new ApiException(HttpStatus.BAD_REQUEST,"USER_ALREADY_ANONYMIZED","Esta conta já foi anonimizada e não pode ser restaurada.");u.setDeletionRequestedAt(null);u.setIsActive(u.getSuspendedAt()==null);}audit(email,"USER_"+a,"USER",id.toString(),reason);return summary(u);}
 @Transactional(readOnly=true) public List<Map<String,Object>> searchVehicles(String query){var q=query==null?"":query.trim();if(q.length()<2)throw new ApiException(HttpStatus.BAD_REQUEST,"SEARCH_TOO_SHORT","Digite ao menos 2 caracteres.");return vehicles.findTop50ByLicensePlateContainingIgnoreCaseOrModelContainingIgnoreCaseOrMakeContainingIgnoreCase(q,q,q).stream().map(v->Map.<String,Object>of("id",v.getId(),"plate",v.getLicensePlate(),"model",Objects.toString(v.getModel(),""),"make",Objects.toString(v.getMake(),""),"driverId",v.getDriver().getId(),"archived",v.getArchivedAt()!=null)).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> recentOffers(){return offers.findTop50ByOrderByDepartureAtDesc().stream().map(o->Map.<String,Object>of("id",o.getId(),"driverId",o.getDriver().getId(),"status",o.getStatus().name(),"departureAt",o.getDepartureAt())).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> reportQueue(String status){var list=status==null||status.isBlank()?reports.findAllByOrderByCreatedAtDesc():reports.findByStatusOrderByCreatedAtDesc(status.trim().toUpperCase(Locale.ROOT));return list.stream().map(r->Map.<String,Object>of("id",r.getId(),"status",r.getStatus(),"reporterId",r.getReporter().getId(),"createdAt",r.getCreatedAt(),"evidenceCount",evidence.findByReportIdOrderByCreatedAtAsc(r.getId()).size())).toList();}
 @Transactional public List<Map<String,Object>> reportEvidence(String email,UUID id){reports.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REPORT_NOT_FOUND","Denúncia não encontrada."));audit(email,"REPORT_EVIDENCE_VIEWED","REPORT",id.toString(),null);return evidence.findByReportIdOrderByCreatedAtAsc(id).stream().map(e->Map.<String,Object>of("messageId",e.getOriginalMessageId(),"senderId",e.getSenderId(),"kind",e.getKind(),"body",Objects.toString(e.getBody(),""),"locationJson",Objects.toString(e.getLocationJson(),""),"sentAt",e.getSentAt(),"mediaIdsJson",e.getMediaIdsJson())).toList();}
 @Transactional public void updateReport(String email,UUID id,String status,String reason){var r=reports.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REPORT_NOT_FOUND","Denúncia não encontrada."));var s=action(status,Set.of("ENVIADA","EM_ANALISE","RESOLVIDA"));r.setStatus(s);audit(email,"REPORT_"+s,"REPORT",id.toString(),reason);notifications.createAndSendNotification(r.getReporter().getId(),"VaiJunto","Sua denúncia foi atualizada.","REPORT_UPDATED","{}",null);}
 @Transactional public void removeEvidenceMedia(String email,UUID reportId,UUID mediaId,String reason){reason(reason);var snapshots=evidence.findByReportIdOrderByCreatedAtAsc(reportId);if(snapshots.stream().noneMatch(s->s.getMediaIdsJson().contains(mediaId.toString())))throw new ApiException(HttpStatus.BAD_REQUEST,"MEDIA_NOT_IN_REPORT","A mídia não pertence à evidência desta denúncia.");storage.deleteReportedMedia(mediaId,reason);for(var snapshot:snapshots)if(snapshot.getMediaIdsJson().contains(mediaId.toString()))snapshot.setMediaIdsJson("[\"MÍDIA REMOVIDA PELO ADMIN\"]");audit(email,"REPORT_MEDIA_REMOVED","REPORT",reportId.toString(),reason);}
 @Transactional(readOnly=true) public List<Map<String,Object>> stickers(){return stickers.findAllByOrderByLabelAsc().stream().map(s->Map.<String,Object>of("id",s.getId(),"code",s.getCode(),"label",s.getLabel(),"assetPath","/stickers/"+s.getId()+"/asset","active",s.isActive())).toList();}
 @Transactional public void setSticker(String email,UUID id,boolean active,String reason){var s=stickers.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"STICKER_NOT_FOUND","Figurinha não encontrada."));s.setActive(active);audit(email,active?"STICKER_ENABLED":"STICKER_DISABLED","STICKER",id.toString(),reason);}
 @Transactional public UUID contact(String email,UUID userId,String body,List<UUID> mediaIds){var attachments=mediaIds==null?List.<UUID>of():mediaIds;if((body==null||body.trim().isBlank())&&attachments.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"MESSAGE_EMPTY","Escreva uma mensagem antes de enviar.");var admin=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));var user=user(userId);var c=conversations.findAdministrative(userId,admin.getId()).orElseGet(()->conversations.save(Conversation.builder().type("ADMINISTRATIVE").participantA(user).adminAccount(admin).lastActivityAt(OffsetDateTime.now()).build()));var message=messages.save(ConversationMessage.builder().conversation(c).adminSender(admin).clientId(UUID.randomUUID()).kind("TEXT").body(body==null?null:body.trim()).deliveredAt(OffsetDateTime.now()).build());attach(attachments,message,c);c.setArchivedAt(null);c.setLastActivityAt(OffsetDateTime.now());audit(email,"ADMIN_CONVERSATION_SENT","USER",userId.toString(),null);notifications.createAndSendNotification(userId,"VaiJunto","Você recebeu uma mensagem administrativa.","ADMIN_MESSAGE","{\"conversationId\":\""+c.getId()+"\"}",null);return c.getId();}
 @Transactional public UUID openAdminConversation(String email,UUID userId){var admin=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));var user=user(userId);return conversations.findAdministrative(userId,admin.getId()).orElseGet(()->conversations.save(Conversation.builder().type("ADMINISTRATIVE").participantA(user).adminAccount(admin).lastActivityAt(OffsetDateTime.now()).build())).getId();}
 @Transactional(readOnly=true) public List<Map<String,Object>> adminConversation(String email,UUID conversationId){var admin=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));var conversation=conversations.findById(conversationId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CONVERSATION_NOT_FOUND","Conversa não encontrada."));if(!"ADMINISTRATIVE".equals(conversation.getType())||!admin.getId().equals(conversation.getAdminAccount().getId()))throw ApiException.conversationForbidden();return messages.findByConversationIdOrderBySentAtAsc(conversationId).stream().<Map<String,Object>>map(m->{var result=new LinkedHashMap<String,Object>();result.put("id",m.getId());result.put("body",m.getBody());result.put("sentAt",m.getSentAt());result.put("fromAdmin",m.getAdminSender()!=null);result.put("sender",m.getAdminSender()!=null?adminLabel(m.getAdminSender()):m.getSender().getName());result.put("media",m.getMedia().stream().filter(x->"ACTIVE".equals(x.getStatus())).map(x->Map.<String,Object>of("id",x.getId(),"contentType",x.getContentType(),"url",storage.adminMediaUrl(x.getId()))).toList());return result;}).toList();}
 @Transactional public UUID sendAdminMessage(String email,UUID conversationId,String body,List<UUID> mediaIds){var attachments=mediaIds==null?List.<UUID>of():mediaIds;if((body==null||body.trim().isBlank())&&attachments.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"MESSAGE_EMPTY","Escreva uma mensagem antes de enviar.");var admin=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));var c=conversations.findById(conversationId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"CONVERSATION_NOT_FOUND","Conversa não encontrada."));if(!"ADMINISTRATIVE".equals(c.getType())||!admin.getId().equals(c.getAdminAccount().getId()))throw ApiException.conversationForbidden();var message=messages.save(ConversationMessage.builder().conversation(c).adminSender(admin).clientId(UUID.randomUUID()).kind("TEXT").body(body==null?null:body.trim()).deliveredAt(OffsetDateTime.now()).build());attach(attachments,message,c);c.setLastActivityAt(OffsetDateTime.now());notifications.createAndSendNotification(c.getParticipantA().getId(),"VaiJunto","Você recebeu uma mensagem de "+adminLabel(admin)+".","ADMIN_MESSAGE","{\"conversationId\":\""+c.getId()+"\"}",null);audit(email,"ADMIN_CONVERSATION_SENT","USER",c.getParticipantA().getId().toString(),null);return c.getId();}
 @Transactional(readOnly=true) public List<Map<String,Object>> tags(){return userTags.findAllByOrderByNameAsc().stream().map(this::tag).toList();}
 @Transactional public Map<String,Object> createTag(String email,String name,String color,String svg){if(name==null||!name.trim().matches("[\\p{L}\\p{N} _-]{2,48}"))throw new ApiException(HttpStatus.BAD_REQUEST,"TAG_NAME_INVALID","A tag deve ter entre 2 e 48 caracteres.");if(color==null||!color.matches("^#[0-9A-Fa-f]{6}$"))throw new ApiException(HttpStatus.BAD_REQUEST,"TAG_COLOR_INVALID","Use uma cor hexadecimal, por exemplo #00AEEF.");if(svg==null||svg.length()>10000||!svg.trim().startsWith("<svg")||svg.toLowerCase(Locale.ROOT).contains("<script"))throw new ApiException(HttpStatus.BAD_REQUEST,"TAG_SVG_INVALID","Informe um SVG válido e seguro.");String normalized=name.trim();if(userTags.existsByNameIgnoreCase(normalized))throw new ApiException(HttpStatus.CONFLICT,"TAG_EXISTS","Já existe uma tag com este nome.");var tag=userTags.save(AdminUserTag.builder().name(normalized).color(color.toUpperCase(Locale.ROOT)).iconSvg(svg.trim()).build());audit(email,"USER_TAG_CREATED","TAG",tag.getId().toString(),null);return tag(tag);}
 @Transactional public List<Map<String,Object>> assignTag(String email,UUID userId,UUID tagId){var user=user(userId);var tag=userTags.findById(tagId).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"TAG_NOT_FOUND","Tag não encontrada."));var id=new AdminUserTagAssignmentId(userId,tagId);if(!tagAssignments.existsById(id)){tagAssignments.save(AdminUserTagAssignment.builder().id(id).user(user).tag(tag).build());audit(email,"USER_TAG_ASSIGNED","USER",userId.toString(),tag.getName());}return tagsFor(userId);}
 @Transactional public List<Map<String,Object>> unassignTag(String email,UUID userId,UUID tagId){if(tagAssignments.existsById(new AdminUserTagAssignmentId(userId,tagId))){tagAssignments.deleteById(new AdminUserTagAssignmentId(userId,tagId));audit(email,"USER_TAG_REMOVED","USER",userId.toString(),tagId.toString());}return tagsFor(userId);}
 /**
  * Prende os anexos à mensagem administrativa. A mídia também passa a apontar
  * para a conversa: é isso que autoriza o usuário do outro lado a baixar pelo
  * endpoint comum de mídia, que checa participação na conversa.
  */
 private void attach(List<UUID> mediaIds,ConversationMessage message,Conversation conversation){for(var id:mediaIds){var object=mediaObjects.findById(id).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"MEDIA_NOT_FOUND","Anexo não encontrado."));if(!"ACTIVE".equals(object.getStatus())||!"ADMIN_MESSAGE".equals(object.getCategory())||object.getMessage()!=null)throw new ApiException(HttpStatus.BAD_REQUEST,"MEDIA_NOT_ATTACHABLE","Anexo indisponível para esta conversa.");object.setConversation(conversation);object.setMessage(message);}}
 private User user(UUID id){return users.findById(id).orElseThrow(ApiException::userNotFound);} private Map<String,Object> summary(User u){var result=new LinkedHashMap<String,Object>();result.put("id",u.getId());result.put("name",u.getName());result.put("fullName",u.getFullName());result.put("email",u.getEmail());result.put("verified",Boolean.TRUE.equals(u.getVerificationBadgeActive()));result.put("verificationStatus",u.getVerificationStatus());result.put("warned",u.getWarnedAt()!=null);result.put("suspended",u.getSuspendedAt()!=null);result.put("deleted",u.getDeletionRequestedAt()!=null);result.put("tags",tagsFor(u.getId()));return result;} private List<Map<String,Object>> tagsFor(UUID userId){return tagAssignments.findByIdUserId(userId).stream().map(a->tag(a.getTag())).toList();} private Map<String,Object> tag(AdminUserTag tag){return Map.of("id",tag.getId(),"name",tag.getName(),"color",tag.getColor(),"iconSvg",tag.getIconSvg());} private String adminLabel(AdminAccount admin){return admin.getEmail().substring(0,admin.getEmail().indexOf('@'));} private void audit(String email,String event,String type,String target,String reason){var a=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));audits.save(AdminAuditEvent.builder().admin(a).eventType(event).targetType(type).targetId(target).reason(reason==null?null:reason.trim()).build());} private static String action(String value,Set<String> allowed){var a=value==null?"":value.trim().toUpperCase(Locale.ROOT);if(!allowed.contains(a))throw new ApiException(HttpStatus.BAD_REQUEST,"ADMIN_ACTION_INVALID","Ação administrativa inválida.");return a;} private static void reason(String value){if(value==null||value.trim().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"ADMIN_REASON_REQUIRED","Informe o motivo da decisão.");}
}
