package com.vaijunto.service;

import com.vaijunto.domain.entities.*;
import com.vaijunto.exception.ApiException;
import com.vaijunto.repository.*;
import java.time.OffsetDateTime;
import java.util.*;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Administrative boundary: report views are limited to immutable selected evidence. */
@Service @RequiredArgsConstructor
public class AdminOperationsService {
 private final AdminAccountRepository admins; private final AdminAuditEventRepository audits; private final UserRepository users; private final MessageReportRepository reports; private final ReportEvidenceSnapshotRepository evidence; private final ChatStickerRepository stickers; private final NotificationService notifications; private final ConversationRepository conversations; private final ConversationMessageRepository messages; private final VehicleRepository vehicles; private final OfferRepository offers; private final MediaStorageService storage;
 @Transactional public Map<String,Object> verify(String email, UUID id,String action,String reason){var u=user(id);var a=action(action,Set.of("GRANT","REJECT","PAUSE","REMOVE"));reason(reason);u.setVerificationBadgeActive("GRANT".equals(a));u.setVerificationStatus(switch(a){case "GRANT"->"VERIFIED";case "REJECT"->"REJECTED";case "PAUSE"->"PAUSED";default->"REMOVED";});u.setVerificationNote(reason.trim());audit(email,"VERIFICATION_"+a,"USER",id.toString(),reason);notifications.createAndSendNotification(id,"VaiJunto","Seu selo de verificação foi atualizado.","VERIFICATION_UPDATED","{}",null);return summary(u);}
 @Transactional public Map<String,Object> moderate(String email,UUID id,String action,String reason){var u=user(id);var a=action(action,Set.of("WARN","CLEAR_WARNING","SUSPEND","RESTORE"));if(!Set.of("CLEAR_WARNING","RESTORE").contains(a))reason(reason);if("WARN".equals(a)){u.setWarnedAt(OffsetDateTime.now());u.setWarningReason(reason.trim());}if("CLEAR_WARNING".equals(a)){u.setWarnedAt(null);u.setWarningReason(null);}if("SUSPEND".equals(a)){u.setIsActive(false);u.setSuspendedAt(OffsetDateTime.now());u.setSuspensionReason(reason.trim());}if("RESTORE".equals(a)){u.setIsActive(true);u.setSuspendedAt(null);u.setSuspensionReason(null);}audit(email,"USER_"+a,"USER",id.toString(),reason);notifications.createAndSendNotification(id,"VaiJunto","Há uma atualização na sua conta. Consulte o canal oficial.","MODERATION_UPDATED","{}",null);return summary(u);}
 @Transactional(readOnly=true) public List<Map<String,Object>> search(String query){var q=query==null?"":query.trim();if(q.length()<2)throw new ApiException(HttpStatus.BAD_REQUEST,"SEARCH_TOO_SHORT","Digite ao menos 2 caracteres.");return users.findTop50ByNameContainingIgnoreCaseOrFullNameContainingIgnoreCaseOrEmailContainingIgnoreCase(q,q,q).stream().map(this::summary).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> searchVehicles(String query){var q=query==null?"":query.trim();if(q.length()<2)throw new ApiException(HttpStatus.BAD_REQUEST,"SEARCH_TOO_SHORT","Digite ao menos 2 caracteres.");return vehicles.findTop50ByLicensePlateContainingIgnoreCaseOrModelContainingIgnoreCaseOrMakeContainingIgnoreCase(q,q,q).stream().map(v->Map.<String,Object>of("id",v.getId(),"plate",v.getLicensePlate(),"model",Objects.toString(v.getModel(),""),"make",Objects.toString(v.getMake(),""),"driverId",v.getDriver().getId(),"archived",v.getArchivedAt()!=null)).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> recentOffers(){return offers.findTop50ByOrderByDepartureAtDesc().stream().map(o->Map.<String,Object>of("id",o.getId(),"driverId",o.getDriver().getId(),"status",o.getStatus().name(),"departureAt",o.getDepartureAt())).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> reportQueue(String status){var list=status==null||status.isBlank()?reports.findAllByOrderByCreatedAtDesc():reports.findByStatusOrderByCreatedAtDesc(status.trim().toUpperCase(Locale.ROOT));return list.stream().map(r->Map.<String,Object>of("id",r.getId(),"status",r.getStatus(),"reporterId",r.getReporter().getId(),"createdAt",r.getCreatedAt(),"evidenceCount",evidence.findByReportIdOrderByCreatedAtAsc(r.getId()).size())).toList();}
 @Transactional public List<Map<String,Object>> reportEvidence(String email,UUID id){reports.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REPORT_NOT_FOUND","Denúncia não encontrada."));audit(email,"REPORT_EVIDENCE_VIEWED","REPORT",id.toString(),null);return evidence.findByReportIdOrderByCreatedAtAsc(id).stream().map(e->Map.<String,Object>of("messageId",e.getOriginalMessageId(),"senderId",e.getSenderId(),"kind",e.getKind(),"body",Objects.toString(e.getBody(),""),"locationJson",Objects.toString(e.getLocationJson(),""),"sentAt",e.getSentAt(),"mediaIdsJson",e.getMediaIdsJson())).toList();}
 @Transactional public void updateReport(String email,UUID id,String status,String reason){var r=reports.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REPORT_NOT_FOUND","Denúncia não encontrada."));var s=action(status,Set.of("ENVIADA","EM_ANALISE","RESOLVIDA"));r.setStatus(s);audit(email,"REPORT_"+s,"REPORT",id.toString(),reason);notifications.createAndSendNotification(r.getReporter().getId(),"VaiJunto","Sua denúncia foi atualizada.","REPORT_UPDATED","{}",null);}
 @Transactional public void removeEvidenceMedia(String email,UUID reportId,UUID mediaId,String reason){reason(reason);var snapshots=evidence.findByReportIdOrderByCreatedAtAsc(reportId);if(snapshots.stream().noneMatch(s->s.getMediaIdsJson().contains(mediaId.toString())))throw new ApiException(HttpStatus.BAD_REQUEST,"MEDIA_NOT_IN_REPORT","A mídia não pertence à evidência desta denúncia.");storage.deleteReportedMedia(mediaId,reason);for(var snapshot:snapshots)if(snapshot.getMediaIdsJson().contains(mediaId.toString()))snapshot.setMediaIdsJson("[\"MÍDIA REMOVIDA PELO ADMIN\"]");audit(email,"REPORT_MEDIA_REMOVED","REPORT",reportId.toString(),reason);}
 @Transactional(readOnly=true) public List<Map<String,Object>> stickers(){return stickers.findAllByOrderByLabelAsc().stream().map(s->Map.<String,Object>of("id",s.getId(),"code",s.getCode(),"label",s.getLabel(),"active",s.isActive())).toList();}
 @Transactional public void setSticker(String email,UUID id,boolean active,String reason){var s=stickers.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"STICKER_NOT_FOUND","Figurinha não encontrada."));s.setActive(active);audit(email,active?"STICKER_ENABLED":"STICKER_DISABLED","STICKER",id.toString(),reason);}
 @Transactional public UUID contact(String email,UUID userId,String body){if(body==null||body.trim().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"MESSAGE_EMPTY","Escreva uma mensagem antes de enviar.");var admin=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));var user=user(userId);var c=conversations.findAdministrative(userId,admin.getId()).orElseGet(()->conversations.save(Conversation.builder().type("ADMINISTRATIVE").participantA(user).adminAccount(admin).lastActivityAt(OffsetDateTime.now()).build()));messages.save(ConversationMessage.builder().conversation(c).adminSender(admin).clientId(UUID.randomUUID()).kind("TEXT").body(body.trim()).deliveredAt(OffsetDateTime.now()).build());c.setArchivedAt(null);c.setLastActivityAt(OffsetDateTime.now());audit(email,"ADMIN_CONVERSATION_SENT","USER",userId.toString(),null);notifications.createAndSendNotification(userId,"VaiJunto","Você recebeu uma mensagem administrativa.","ADMIN_MESSAGE","{\"conversationId\":\""+c.getId()+"\"}",null);return c.getId();}
 private User user(UUID id){return users.findById(id).orElseThrow(ApiException::userNotFound);} private Map<String,Object> summary(User u){return Map.of("id",u.getId(),"name",u.getName(),"fullName",u.getFullName(),"email",u.getEmail(),"verified",Boolean.TRUE.equals(u.getVerificationBadgeActive()),"verificationStatus",u.getVerificationStatus(),"warned",u.getWarnedAt()!=null,"suspended",u.getSuspendedAt()!=null);} private void audit(String email,String event,String type,String target,String reason){var a=admins.findByEmail(email).orElseThrow(()->new ApiException(HttpStatus.FORBIDDEN,"ADMIN_NOT_FOUND","Administrador inválido."));audits.save(AdminAuditEvent.builder().admin(a).eventType(event).targetType(type).targetId(target).reason(reason==null?null:reason.trim()).build());} private static String action(String value,Set<String> allowed){var a=value==null?"":value.trim().toUpperCase(Locale.ROOT);if(!allowed.contains(a))throw new ApiException(HttpStatus.BAD_REQUEST,"ADMIN_ACTION_INVALID","Ação administrativa inválida.");return a;} private static void reason(String value){if(value==null||value.trim().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"ADMIN_REASON_REQUIRED","Informe o motivo da decisão.");}
}
