package com.vaijunto.service;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.ByteBuffer;
import java.time.Instant;

/** RFC 6238 compatible six-digit TOTP verifier; the secret is provisioned by developers, never generated by an API. */
final class Totp {
    private Totp() {}
    static boolean verify(String base32Secret, String submitted) {
        if (submitted == null || !submitted.matches("\\d{6}")) return false;
        long now = Instant.now().getEpochSecond() / 30;
        for (long step = now - 1; step <= now + 1; step++) if (code(base32Secret, step).equals(submitted)) return true;
        return false;
    }
    private static String code(String secret, long step) {
        try {
            Mac mac = Mac.getInstance("HmacSHA1"); mac.init(new SecretKeySpec(decode(secret), "HmacSHA1"));
            byte[] hash = mac.doFinal(ByteBuffer.allocate(8).putLong(step).array()); int offset = hash[hash.length - 1] & 15;
            int value = ((hash[offset] & 127) << 24) | ((hash[offset + 1] & 255) << 16) | ((hash[offset + 2] & 255) << 8) | (hash[offset + 3] & 255);
            return String.format("%06d", value % 1_000_000);
        } catch (Exception e) { return ""; }
    }
    private static byte[] decode(String input) {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; String normalized = input.replace("=", "").replaceAll("\\s", "").toUpperCase();
        ByteBuffer out = ByteBuffer.allocate(normalized.length() * 5 / 8); int buffer = 0, bits = 0;
        for (char c : normalized.toCharArray()) { int v = chars.indexOf(c); if (v < 0) throw new IllegalArgumentException("Invalid TOTP secret"); buffer = (buffer << 5) | v; bits += 5; if (bits >= 8) { out.put((byte) (buffer >> (bits - 8))); bits -= 8; } }
        byte[] result = new byte[out.position()]; out.flip(); out.get(result); return result;
    }
}
