package com.vaijunto.service;
import com.vaijunto.domain.entities.*; import com.vaijunto.dto.*; import com.vaijunto.exception.ApiException; import com.vaijunto.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.OffsetDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class VehicleService {
 private final VehicleRepository vehicles; private final UserRepository users; private final OfferRepository offers;
 @Transactional(readOnly=true) public List<VehicleDto> list(String email){return vehicles.findByDriverIdAndArchivedAtIsNullOrderByIsDefaultDescCreatedAtDesc(user(email).getId()).stream().map(VehicleDto::from).toList();}
 @Transactional public VehicleDto create(VehicleRequest r,String email){var u=user(email);String plate=plate(r.getLicensePlate());if(vehicles.existsByLicensePlateAndArchivedAtIsNull(plate))throw new IllegalArgumentException("Não foi possível usar esta placa. Revise os dados ou fale com o suporte.");var v=Vehicle.builder().driver(u).licensePlate(plate).build();apply(v,r); if(vehicles.findByDriverIdAndArchivedAtIsNullOrderByIsDefaultDescCreatedAtDesc(u.getId()).isEmpty())v.setIsDefault(true);return VehicleDto.from(vehicles.save(v));}
 @Transactional public VehicleDto update(UUID id,VehicleRequest r,String email){var v=owned(id,email);String plate=plate(r.getLicensePlate());if(!plate.equals(v.getLicensePlate())&&vehicles.existsByLicensePlateAndArchivedAtIsNull(plate))throw new IllegalArgumentException("Não foi possível usar esta placa. Revise os dados ou fale com o suporte.");v.setLicensePlate(plate);apply(v,r);return VehicleDto.from(v);}
 @Transactional public VehicleDto makeDefault(UUID id,String email){var v=owned(id,email);vehicles.findByDriverIdAndArchivedAtIsNullOrderByIsDefaultDescCreatedAtDesc(v.getDriver().getId()).forEach(x->x.setIsDefault(false));v.setIsDefault(true);return VehicleDto.from(v);}
 @Transactional public void archive(UUID id,String email){var v=owned(id,email); if(offers.countByDriverIdAndStatusIn(v.getDriver().getId(),List.of(com.vaijunto.domain.enums.OfferStatus.ACTIVE,com.vaijunto.domain.enums.OfferStatus.FULL))>0)throw new IllegalArgumentException("Este veículo está em uma carona futura ou em andamento e não pode ser excluído.");v.setArchivedAt(OffsetDateTime.now());v.setIsDefault(false);}
 private User user(String email){return users.findByEmail(email).orElseThrow(ApiException::userNotFound);} private Vehicle owned(UUID id,String email){var v=vehicles.findById(id).orElseThrow(()->new IllegalArgumentException("Veículo não encontrado."));if(v.getArchivedAt()!=null||!v.getDriver().getEmail().equals(email))throw new ApiException(org.springframework.http.HttpStatus.NOT_FOUND,"VEHICLE_NOT_FOUND","Veículo não encontrado.");return v;}
 private String plate(String p){String x=p==null?"":p.replaceAll("[^A-Za-z0-9]","").toUpperCase();if(!x.matches("[A-Z]{3}[0-9][A-Z0-9][0-9]{2}"))throw new IllegalArgumentException("Informe uma placa válida.");return x;}
 private void apply(Vehicle v,VehicleRequest r){if(r.getCapacity()==null||r.getCapacity()<1||r.getCapacity()>20||r.getVehicleType()==null)throw new IllegalArgumentException("Informe tipo e capacidade válidos.");v.setModel(blank(r.getModel()));v.setMake(blank(r.getMake()));v.setTrim(blank(r.getTrim()));v.setYear(r.getYear());v.setColor(blank(r.getColor()));v.setFuel(blank(r.getFuel()));v.setAverageConsumption(r.getAverageConsumption());v.setPhotoUrl(blank(r.getPhotoUrl()));v.setCapacity(r.getCapacity());v.setVehicleType(r.getVehicleType());} private String blank(String s){return s==null?null:s.trim();}
}
